n = int(input('Digite um número '))
print('O dobro do valor é {}'.format(n*2))
print('O triplo do valor é {}'.format((n*3)))
print('A raiz quadrada do valor é {:.3}'.format(n**(1/2)))
print('n({}) = n * 2 = {}'.format(n,n*2))
print('n({}) = n * 3 = {}'.format(n,n*3))
print('n({}) = n ** (1/2) = {:.3}'.format(n,n**(1/2)))
