m1 = float(input('Digite a primeira Nota\n'))
m2 = float(input('Digite a segunda nota\n'))
print('A média aritmética é de {}'.format((m1+m2)/2))
print(' Primeira Nota: {}'.format(m1))
print(' Segunda  Nota: {}'.format(m2))
print(' Média   Final: {}'.format((m1+m2)/2))
print(' ({} + {})/2 = {}'.format(m1,m2,(m1+m2)/2))